name: Publish Snapshot

on:
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate new version tag (dry-run)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          tag_prefix: v
          dry_run: 'true'

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: slomkarafa/x11vnc-novnc-agent

      - name: Build and push Docker
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: slomkarafa/x11vnc-novnc-agent:${{ steps.tag_version.outputs.new_version }}-${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}